- name: install networking components
  apt:
    name: "{{ item }}"
    state: present
    default_release: xenial-updates/newton
  with_items:
    - neutron-plugin-linuxbridge-agent

- name: (COMPUTE) replace neutron.conf
  template: src=neutron.conf.j2 dest="/etc/neutron/neutron.conf" owner=root group=root mode=0644
  notify:
    - restart nova-compute
    - restart linuxbridge-agent

- name: (COMPUTE) replace linuxbridge_agent.ini
  template: src=linuxbridge_agent.ini.j2 dest="/etc/neutron/plugins/ml2/linuxbridge_agent.ini" owner=root group=root mode=0644
  notify:
    - restart nova-compute
    - restart linuxbridge-agent

