- name: (CLOUDLET) install fabric/openssh/git
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - fabric
    - git
    - openssh-server

- name: (CLOUDLET) checkout elijah-provisioning code from github
  git:
    repo: https://github.com/cmusatyalab/elijah-provisioning.git
    dest: ~/elijah-provisioning

- name: (CLOUDLET) install library using fabric
  shell: fab --user {{local_user}} --password {{local_user_pw}} install
  args:
    chdir: ~/elijah-provisioning

- name: (CLOUDLET) uninstall pbr installed with elijah-provisioning as it conflicts with openstack python clients
  pip:
    name: pbr
    state: absent

- name: (CLOUDLET) hold qemu-kvm/libvirt-bin packages to prevent updates
  command: "apt-mark hold {{ item }}"
  with_items:
    - qemu-kvm
    - libvirt-bin


